# Generated by Django 2.2.6 on 2019-10-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название планеты')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Текст вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='TestTrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_code', models.CharField(max_length=50, verbose_name='Код ордена')),
                ('recruit', models.ManyToManyField(to='main.QuestionsList')),
            ],
        ),
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Planet')),
                ('recruits', models.ManyToManyField(to='main.Recruit', verbose_name='Рекруты этого Ситха')),
            ],
        ),
        migrations.CreateModel(
            name='ShadowHand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Recruit')),
                ('sith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Sith')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(verbose_name='Ответ рекрута')),
                ('Recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Recruit', verbose_name='Рекрут')),
                ('question', models.ForeignKey(on_delete='Вопрос', to='main.QuestionsList')),
            ],
        ),
    ]
