# Generated by Django 2.2.6 on 2019-10-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191003_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testtrial',
            old_name='recruit',
            new_name='questions',
        ),
    ]
