# Generated by Django 2.2.6 on 2019-10-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191003_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ответ рекрута'),
        ),
    ]
