# Generated by Django 2.2.6 on 2019-10-03 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191003_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionslist',
            old_name='question',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='answer',
            name='recruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.Recruit', verbose_name='Рекрут'),
        ),
    ]
